FROM ruby:3.2.3
# Ruby 3.2.3の公式イメージをベースに使用

ENV LANG C.UTF-8
# 環境変数LANGをC.UTF-8に設定（ロケール設定）

ENV TZ Asia/Tokyo
# 環境変数TZをAsia/Tokyoに設定（タイムゾーン設定）

RUN apt-get update -qq \
# パッケージリストを静かに更新

&& apt-get install -y ca-certificates curl gnupg \
# 必要なパッケージ（ca-certificates, curl, gnupg）をインストール

&& mkdir -p /etc/apt/keyrings \
# ディレクトリ/etc/apt/keyringsを作成

&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
# NodeSourceのGPGキーをダウンロードし、dearmorして保存

&& NODE_MAJOR=20 \
# 環境変数NODE_MAJORを20に設定

&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
# Node.js 20.xのリポジトリを追加

&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
# YarnのGPGキーをダウンロードして追加

&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# Yarnのリポジトリを追加

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim
# パッケージリストを更新し、build-essential, libpq-dev, nodejs, yarn, vimをインストール

RUN mkdir /myapp
# ディレクトリ/myappを作成

WORKDIR /myapp
# 作業ディレクトリを/myappに設定

RUN gem install bundler
# Bundlerをインストール

COPY . /myapp
# 現在のディレクトリの内容をコンテナの/myappにコピー